# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirako < Formula
  desc "Official CLI for Mirako AI platform - Create and manage AI avatars, interactive sessions, and AI media generation"
  homepage "https://mirako.ai"
  version "1.2.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.2.0/mirako-cli_Darwin_x86_64.tar.gz"
      sha256 "bd11a08d193254b84d79053f08dfbd33528f1b163d6b916616f91dbccdef49e8"

      def install
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.2.0/mirako-cli_Darwin_arm64.tar.gz"
      sha256 "1a5808685f066164dc2a107ead6da72b22c3d12d7e7afa4e02c54005385f4877"

      def install
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.2.0/mirako-cli_Linux_x86_64.tar.gz"
      sha256 "7e1e5cf20f8a67019fc6e0759a5a79f335ed8ba2e640f91d7f9e17c4c6847beb"
      def install
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.2.0/mirako-cli_Linux_arm64.tar.gz"
      sha256 "3f03299bd01a2ccd007c2c9cb29777f1982661432a5d79228aea304792d54e11"
      def install
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
  end

  test do
    system "#{bin}/mirako --version"
  end
end
