# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mirako < Formula
  desc "Official CLI for Mirako AI platform - Create and manage AI avatars, interactive sessions, and AI media generation"
  homepage "https://mirako.ai"
  version "1.4.0"
  license "MIT"

  depends_on "git" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.4.0/mirako-cli_Darwin_x86_64.tar.gz"
      sha256 "d98fd3391bc4e7b940d57ff53ae44197000028a4e3dc1b011c32fd49618ac57c"

      define_method(:install) do
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.4.0/mirako-cli_Darwin_arm64.tar.gz"
      sha256 "60cf9c2561b83de2991bad806b3332983a6d198e42ca3ed2e12cdccdc6e85fa7"

      define_method(:install) do
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.4.0/mirako-cli_Linux_x86_64.tar.gz"
      sha256 "e54692d7ee9f3f844e47482ddabdf798391b6810fe309da5a9d45420c5da6b07"
      define_method(:install) do
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com//mirako-ai/mirako-cli/releases/download/v1.4.0/mirako-cli_Linux_arm64.tar.gz"
      sha256 "a6ea0dcc2b677a275108ed42abb566892ed1d4734c3618bcf9ee1c6866296d09"
      define_method(:install) do
        bin.install "mirako"
        generate_completions_from_executable(bin/"mirako", "completion")
      end
    end
  end

  test do
    system "#{bin}/mirako --version"
  end
end
